### ISSUE TITLE
README: fix badges

### ISSUE THREAD

**Issue by mhinz** [neovim/pynvim#376]
I just noticed that the `Scrutinizer` and `coverage` badges are broken. 

A look at https://scrutinizer-ci.com/g/neovim/pynvim/?branch=master suggests that they have to get enabled again.

I assume this happened when the repo was renamed.

**Comment by justinmk** [comment]
it's not clear. i updated what I could , but it seems like scrutinzer now expects specific things in the yml.

https://scrutinizer-ci.com/docs/build/code_coverage

https://scrutinizer-ci.com/docs/code_rating_system

The "coverage" tool doesn't work for some reason, but otherwise in https://scrutinizer-ci.com/g/neovim/python-client/?branch=master you can see that the other badges never worked.

see also https://github.com/neovim/pynvim/commit/22e59195f2acfce31db6067ac7b5c67aefc5e16b
